### ISSUE TITLE
src/_posts/the-complete-guide-to-starting-a-blog-in-nextjs-and-mdx/_mdx_bundler_entry_point.mdx:11:21: error: Could not resolve "./404-not-found.png"     11 │ import NotFound from './404-not-found.png';

### ISSUE THREAD

**Issue by deadcoder0904** [Arcath/remark-plugin-colocate-images#3]
I have my content under `src/_posts`. It essentially has 3 sub-folders: `essay`, `tutorial`, & `snippet` where all my blogs are available.

I have a `getPostBySlug` function that essentially is a copy of [this](https://github.com/delbaoliveira/website/blob/main/lib/mdx.ts#L53-L78):

```tsx
const ROOT_PATH = process.cwd()
export const POSTS_PATH = path.join(ROOT_PATH, 'src/_posts')
const PUBLIC_PATH = path.join(ROOT_PATH, 'public')

export const getPostBySlug = async (postType: 'essay' | 'tutorial' | 'snippet', slug: string) => {
	const source = fs.readFileSync(path.join(POSTS_PATH, postType, slug, 'index.mdx'), 'utf8')

	const { code, frontmatter } = await bundleMDX(source, {
		cwd: path.join(POSTS_PATH, slug),
		xdmOptions: (options) => {
			options.remarkPlugins = [...(options?.remarkPlugins ?? []), slugPlugin, gfmPlugin]

			return options
		},
		esbuildOptions: (options) => {
			options.outdir = path.join(PUBLIC_PATH, slug)
			options.loader = {
				...options.loader,
				'.png': 'file',
			}
			options.publicPath = PUBLIC_PATH

			options.write = true

			return options
		},
	})

	const meta = {
		...frontmatter,
		slug,
	} as Meta

	return {
		meta,
		code,
	}
}
```

I think it's perfect as I saw the `path` using `console.log` but I'm still getting an error:

>  src/_posts/the-complete-guide-to-starting-a-blog-in-nextjs-and-mdx/_mdx_bundler_entry_point.mdx:11:21: error: Could not resolve "./404-not-found.png"
    11 │ import NotFound from './404-not-found.png';

The `import NotFound from './404-not-found.png';` is from a blog in my `.mdx` file. How do I solve it?

Another question is what is the `publicPath`? I can't really understand it from the documentation.

Furthermore, there should be a note that if you're using `mdx-bundler`, then this package is not needed as it does the same thing if I'm not wrong.

**Edit:** I did try to place the `import` at the top & used `remark-mdx-images` but it didn't work either. Additionally, I tried [this solution](https://github.com/kentcdodds/mdx-bundler/issues/56) but it doesn't work. I am doing the same thing except I have 3 sub-folders named `essay`, `tutorial`, & `snippet` instead of 1 `blog` folder like in [this repo](https://github.com/podfinkx/nextjs-esbuild-error-example).

**Edit 2:** I also tried the following:

```ts
options.outdir = path.join(PUBLIC_PATH, postType, slug)
options.publicPath = slug
```

but it also doesn't work. I am also not sure if `publicPath` needs trailing `/` or not.

**Comment by deadcoder0904** [comment]
@Arcath ping :)

**Comment by Arcath** [comment]
@deadcoder0904 You are right that mdx-bundler now supports doing this internally without the need for this plugin.

I wrote up how to use mdx-bundler with images on my blog https://www.arcath.net/2021/04/images-with-mdx-bundler and my site bundles them using this: https://github.com/Arcath/arcath.net-next/blob/main/lib/functions/prepare-mdx.ts

**Comment by deadcoder0904** [comment]
@Arcath yeah, I've already read those blog posts & searched every Github project that uses `mdx-bundler` but still facing an issue. I'm in the middle of creating a repro. Can you take a quick look if I'm doing something wrong?

**Comment by deadcoder0904** [comment]
I've created https://github.com/deadcoder0904/mdx-bundler-images-error as a repro. It'll be really helpful if you can take a look as I'm trying to make this thing unsuccessfully work for 2 weeks now 😂

**Comment by Arcath** [comment]
@deadcoder0904 No problem.

Had a look and got it to build on my machine here.

https://github.com/deadcoder0904/mdx-bundler-images-error/blob/main/src/utils/mdx.tsx#L49 needs to be `const cwd = path.join(POSTS_PATH, postType, slug)` so its the path of the `index.mdx`

**Comment by deadcoder0904** [comment]
Holy shit, thanks man. [This commit](https://github.com/deadcoder0904/mdx-bundler-images-error/commit/2cb95e51aae376870b25032d0c91ca7170bd9ecf) fixed it.

Had to change something else too :)

**Comment by deadcoder0904** [comment]
Bdw, still don't understand what the `publicPath` must be which was the source of confusion.

Same with `cwd`. I thought `cwd` must be the directories like `essay` & `tutorial` in my case but turns out I had to point out to the directories inside it.

**Comment by Arcath** [comment]
`cwd` is the directory your mdx is in. So for relative imports to work the same as _normal_ it needs to be the path of the directory the mdx file is in.

`publicPath` is the path to the directory the images will be in on the webserver so that mdx can set the image source as it generates.

**Comment by deadcoder0904** [comment]
> `cwd` is the directory your mdx is in. So for relative imports to work the same as _normal_ it needs to be the path of the directory the mdx file is in.

Now makes sense. I guess an `examples/` folder like Next.js has would be cool for `mdx-bundler`. One for simple solutions like yours & one for subdirectories like mine. It definitely confused me for far too long.

> `publicPath` is the path to the directory the images will be in on the webserver so that mdx can set the image source as it generates.

I thought `publicPath` should be `path.join(postType, slug)` because in your simple example it is everything after `public/` folder.

**Comment by deadcoder0904** [comment]
@Arcath is there a reason why GIFs don't work without `remark-mdx-images`?

If I comment [this line](https://github.com/deadcoder0904/mdx-bundler-images-error/blob/4ca6f2e95c47141f3db325cbbb250719ba8fd040/src/utils/mdx.ts#L58), GIF doesn't work.

If I uncomment it, it works.

I have already enabled GIF loader under `options.loader` already.

Should I open an issue on MDX Bundler?

# Edit:

Only `import` syntax works, markdown syntax doesn't. However, markdown syntax works for images `.png`. I'm not sure why it shouldn't work for GIFs as well. Or is this an MDX issue?
